/*
 * Copyright 2015 Sonata Software. All rights reserved. Software, Inc.  All rights reserved.
 */

package com.sonata.generic.automation.fixture.configuration;

/**
 * Interface for a factory used to create {@link ConfigurationParser} instances
 * to parse fixture configuration data.
 */
public interface ConfigurationParserFactory
{
   /**
    * Creates a {@link ConfigurationParser} that makes use of an automation
    * {@link com.sage.swt.automation.browser.Browser Browser} object created
    * with the specified browser settings.
    * 
    * @param browserSettings
    *           The settings used for creating a specific kind of automation
    *           {@link com.sage.swt.automation.browser.Browser Browser} object
    *           (to be used by the fixture properties generated by the parser),
    *           or null to create an automation {@code Browser} object with
    *           default settings.
    * 
    * @return A {@link ConfigurationParser} that makes use of an automation
    *         browser object created with the specified browser settings.
    * 
    * @throws IllegalArgumentException
    *            The browser settings are invalid (note that null or empty
    *            browser settings are valid, though).
    */
   ConfigurationParser createConfigurationParser(String browserSettings);
}
